application: icsscgdoc
version: 1
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- channel_presence

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /fonts
  static_dir: static/fonts

- url: /.*
  script: doc.application
